---
- name: Install and configure apache 2
  hosts: all
  become: yes

  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Ensure apache2 is running
      service:
       name: apache2
       state: started
       enabled: yes
